### ISSUE TITLE
Connecting to multiple devices leads to a strange behavior

### ISSUE THREAD

**Issue by Tineler** [relayr/node-relayr#4]
If I'm using the following code, relayr emits the 'data'-event 6 times for each device with the same topic and msg.

     relayr.user(token, function (err, user) {
        relayr.devices(user.id, token, function (err, devices) {
            devices.forEach(function (device) {
                relayr.connect(token, device.id);
            });
        });
    })

    relayr.on('data', function (topic, msg) {
        app.io.emit('news', { hello: msg });
    });

**Comment by paulhopton** [comment]
fixed in version 0.3.8
